In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("IMDB Dataset.csv")

In [12]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

### **Lower Casing**

In [ ]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [14]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [16]:
df.shape

(50000, 2)

In [19]:
df['review'].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

### **HTML Tags Removing(unimportant things removal)**

In [20]:
import re
def remove_htmlTags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [21]:
df['review'].apply(remove_htmlTags)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [22]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

### **Removng URL**

In [23]:
def removeURL(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [25]:
import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [26]:
exclude = string.punctuation

In [36]:
def removePunctuation(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [37]:
text = "Hello, , my name is PRAjwal? and I'am a data scientiest"

In [38]:
start = time.time()
print(removePunctuation(text))
time1 = time.time() - start
print(time1)

Hello  my name is PRAjwal and Iam a data scientiest
0.00018668174743652344

In [39]:
def removePunctuation1(text):
    return text.translate(str.maketrans('','',exclude))

In [ ]:
start = time.time()
print(removePunctuation1(text))
time2 = time.time() - start
print(time2)

Hello  my name is PRAjwal and Iam a data scientiest
0.00018668174743652344

In [41]:
time1/time2

0.7543352601156069

### **Chat Word Treatment**

In [43]:
chat_words = {
"A3": "Anytime, Anywhere, Anyplace",
"ADIH": "Another Day In Hell",
"AFK":"Away From Keyboard",
"AFAIK":"As Far As I Know",
"ASAP":"As Soon As Possible",
"ASL":"Age, Sex, Location",
"ATK ":" At The Keyboard",
"ATM":"At The Moment",
"BAE":"Before Anyone Else",
"BAK":"Back At Keyboard",
"BBL":"Be Back Later",
"BBS":"Be Back Soon",
"BFN":"Bye For Now",
"B4N":"Bye For Now",
"BRB":"Be Right Back",
"BRUH":"Bro",
"BRT":"Be Right There",
"BSAAW":"Big Smile And A Wink",
"BTW":"By The Way",
"BWL":"Bursting With Laughter",
"CSL":"Can’t Stop Laughing",
"CU":"See You",
"CUL8R":"See You Later",
"CYA":"See You",
"DM":"Direct Message",
"FAQ":"Frequently Asked Questions",
"FC":"Fingers Crossed",
"FIMH":"Forever In My Heart",
"FOMO":"Fear Of Missing Out",
"FR":"For Real",
"FWIW":"For What It's Worth",
"FYP":"For You Page",
"FYI":"For Your Information",
"G9":"Genius",
"GAL":"Get A Life",
"GG":"Good Game",
"GMTA":"Great Minds Think Alike",
"GN":"Good Night",
"GOAT":"Greatest Of All Time",
"GR8":"Great!",
"HBD":"Happy Birthday",
"IC":"I See",
"ICQ":"I Seek You",
"IDC":"I Don’t Care",
"IDK":"I Don't Know",
"IFYP":"I Feel Your Pain",
"ILU":"I Love You",
"ILY":"I Love You",
"IMHO":"In My Honest/Humble Opinion",
"IMU":"I Miss You",
"IMO":"In My Opinion",
"IOW":"In Other Words",
"IRL":"In Real Life",
"IYKYK":"If You Know, You Know",
"JK":"Just Kidding",
"KISS":"Keep It Simple, Stupid",
"L":"Loss",
"L8R":"Later",
"LDR":"Long Distance Relationship",
"LMK":"Let Me Know",
"LMAO":"Laughing My A** Off",
"LOL":"Laughing Out Loud",
"LTNS":"Long Time No See",
"M8":"Mate",
"MFW":"My Face When",
"MID":"Mediocre",
"MRW":"My Reaction When",
"MTE":"My Thoughts Exactly",
"NVM":"Never Mind",
"NRN":"No Reply Necessary",
"NPC":"Non-Player Character",
"OIC":"Oh I See",
"OP":"Overpowered",
"PITA":"Pain In The A**",
"POV":"Point Of View",
"PRT":"Party",
"PRW":"Parents Are Watching",
"ROFL":"Rolling On The Floor Laughing",
"ROFLOL":"Rolling On The Floor Laughing Out Loud",
"ROTFLMAO":"Rolling On The Floor Laughing My A** Off",
"RN":"Right Now",
"SK8":"Skate",
"STATS":"Your Sex And Age",
"SUS":"Suspicious",
"TBH":"To Be Honest",
"TFW":"That Feeling When",
"THX":"Thank You",
"TIME":"Tears In My Eyes",
"TLDR":"Too Long, Didn’t Read",
"TNTL":"Trying Not To Laugh",
"TTFN":"Ta-Ta For Now!",
"TTYL":"Talk To You Later",
"U":"You",
"U2":"You Too",
"U4E":"Yours For Ever",
"W":"Win",
"W8":"Wait...",
"WB":"Welcome Back",
"WTF":"What The F**k",
"WTG":"Way To Go!",
"WUF":"Where Are You From?",
"WYD":"What You Doing?",
"WYWH":"Wish You Were Here",
"ZZZ":"Sleeping, Bored, Tired"
}

In [44]:
def chatConverion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [45]:
chatConverion("U are the best")

'You are the best'

In [49]:
chatConverion("DM")

'Direct Message'

### **Spelling Correction**